config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  validates :description, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
    if !session[:current_user_id]
      redirect_to root_path
    end

    @article = Article.new
  end

  def create

    @article = Article.new(article_params)
    @article.user_id = session[:current_user_id]
    @user = User.find(session[:current_user_id])
    if @article.save
      flash[:notice] = "Article successfully created"
      redirect_to user_path(@user)
    else
      render :new
    end
  end


  private

  def article_params
    params.require(:article).permit(:description, :user_id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    #render plain: params[:user].inspect
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User successfully created"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    session[:current_user_id] = @user.id
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User info successfully updated"
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    flash[:notice] = "User (" + @user.first_name + " " + @user.last_name + ") successfully deleted"
    @user.destroy
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :age)
    end

    def set_user
      @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article_form.html.erb
<% if @article.errors.any? %>


    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

      <% @article.errors.full_messages.each do |msg| %>

          <%= msg %> <br>

      <% end %>
    </div>


<% end %>


<%= form_for @article do |u| %>

    <div class="form-group">
      <%= u.label :description %>
      <%= u.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= u.submit 'Submit', :class => "btn btn-primary" %>
    </div>

<% end %>

app/views/articles/new.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Create New Article</h1>
    <p>Fill up the form to create a new article</p>
    <p>
      <%= link_to "Back", "../users/#{session[:current_user_id]}", class: "btn btn-primary btn-lg" %>
    </p>
  </div>

  <div class="container">
    <%= render partial: 'articles/article_form' %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_user_form.html.erb
<% if @user.errors.any? %>


    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

      <% @user.errors.full_messages.each do |msg| %>

          <%= msg %> <br>

      <% end %>
    </div>


<% end %>


<%= form_for @user do |u| %>

    <div class="form-group">
      <%= u.label :first_name %>
      <%= u.text_field :first_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= u.label :last_name %>
      <%= u.text_field :last_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= u.label :age %>
      <%= u.text_field :age, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= u.submit 'Submit', :class => "btn btn-primary" %>
    </div>

<% end %>

app/views/users/edit.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Edit User</h1>
    <p>Edit user information</p>
    <p>
      <%= link_to "Back", root_path, class: "btn btn-primary btn-lg" %>
    </p>
  </div>

  <div class="container">

    <%= render partial: 'users/user_form' %>

  </div>

</div>

app/views/users/index.html.erb
<div class="jumbotron">
	<div class="container">
		<h1>Users</h1>
		<p>List</p>
		<p>
      <%= link_to "Create User", new_user_path, class: "btn btn-primary btn-lg" %>
		</p>
	</div>
</div>

<div class="container">

  <% flash.each do |name, msg| %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>

      </div>
  <% end %>

  <% @users.each do |user| %>
      <div class="well well-sm">
        <h3><%= user.first_name + ' ' + user.last_name %></h3>
        <h4>Articles: <%= user.articles.length %> </h4>
        <%= link_to "View", user_path(user), class: "btn btn-primary btn-xs" %>
        <%= link_to "Edit", edit_user_path(user), class: "btn btn-warning btn-xs" %>
        <%= link_to "Delete", user_path(user), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger btn-xs" %>
      </div>
  <% end %>

</div>

app/views/users/new.html.erb
<div class="jumbotron">
	<div class="container">
		<h1>Create New User</h1>
		<p>Fill up the form to create a new user</p>
		<p>
			<%= link_to "Back", root_path, class: "btn btn-primary btn-lg" %>
		</p>
	</div>

  <div class="container">

    <%= render partial: 'users/user_form' %>

  </div>

</div>

app/views/users/show.html.erb
<div class="jumbotron">
	<div class="container">
		<h1><%= @user.first_name + ' ' + @user.last_name %></h1>
    <p>&nbsp;</p>
    <p>
      <%= link_to "Back", root_path, class: "btn btn-primary btn-lg" %>
    </p>
	</div>
</div>

<div class="container">

  <h2>Articles</h2>

  <% flash.each do |name, msg| %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>

      </div>
  <% end %>

  <%= link_to "Create Article", new_article_path, class: "btn btn-primary btn-md" %>

  <table class="table table-striped">
    <thead>
      <th>ID</th>
      <th>Description</th>
      <th>Date Created</th>
      <th>Action</th>
    </thead>

    <tbody>

    <% @user.articles.each do |article| %>

    <tr>
      <td><%= article.id %></td>
      <td><%= article.description %></td>
      <td><%= article.created_at %></td>
      <td>
        <%= link_to "View", article_path(article), class: "btn btn-primary btn-xs" %>
        <%= link_to "Edit", edit_article_path(article), class: "btn btn-warning btn-xs" %>
        <%= link_to "Delete", article_path(article), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger btn-xs" %>

      </td>
    </tr>

    <% end %>

    </tbody>

  </table>

</div>